<?php $this->layout()->setLayout('admin'); ?>

<?php echo $this->render('global/topbar_admin.phtml'); ?>

<div class="row">
	<div class="span12">
		<h1>Benvenuto <small><?php echo $this->identity->fullname; ?></small></h1>
		<p class="lead">Spiaggia Online 1.0 è il software dove prenotare ombrellone sdraio e lettini online...</p>
	    <hr />
	</div>
</div>

<?php echo $this->render('global/copyright_admin.phtml'); ?>