<?php $this->layout()->setLayout('admin'); ?>

<?php echo $this->render('global/topbar_admin.phtml'); ?>

<div class="row">
	<div class="twelve columns">
		<h1 class="subheader">Prenotazioni</h1>
		<p>...</p>
		<hr />
	</div>
</div>

<div class="row">
	<div class="twelve columns">
		<table class="twelve">
			<thead>
				<tr>
					<th>Dettaglio</th>
					<th>Numero</th>
					<th>Cliente</th>
					<th>Stato</th>
					<th>Data</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><a href="<?php echo $this->url(array('controller' => 'reservations', 'action' => 'detail', 'id' => 0)); ?>" class="button">Dettaglio</a></td>
					<td>...</td>
					<td>...</td>
					<td>...</td>
					<td>...</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<?php echo $this->render('global/copyright_admin.phtml'); ?>