<br>

<div class="row">
    <div class="span12">
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <a class="brand" href="">Administrator</a>
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url(array('controller' => 'settings', 'action' => 'index'), null, true); ?>"><i class="icon-home icon-white"></i> Dashboard</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), null, true); ?>"><i class="icon-list icon-white"></i> Gestione Lidi</a></li>
                    <li><a role="button" href="#logoutModal" data-toggle="modal"><i class="icon-off icon-white"></i> Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="logoutModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Logout</h3>
    </div>
    <div class="modal-body">
        <p>Sei sicuro di voler chiudere la finestra?</p>
    </div>
    <div class="modal-footer">
        <a class="btn btn-danger" href="<?php echo $this->url(array('controller' => 'settings', 'action' => 'logout'), null, true); ?>">Logout</a>
    </div>
</div>