<br>

<div class="row">
    <div class="span12">
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <a class="brand" href="<?php echo $this->url(array('controller' => 'dashboard', 'action' => 'index'), null, true); ?>">Administrator</a>
                <ul class="nav">
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> Configurazione <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'edit'), null, true); ?>"><i class="icon-plus"></i> Modifica Profilo</a></li>
                            <li><a href="/"><i class="icon-pencil"></i> Anteprima Booking</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> Calendario <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'calendar', 'action' => 'daily'), null, true); ?>"><i class="icon-plus"></i> Disponibilit&agrave; giornaliera</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'calendar', 'action' => 'period'), null, true); ?>"><i class="icon-pencil"></i> Disponibilit&agrave; per periodi</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> Servizi <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'facility', 'action' => 'new'), null, true); ?>"><i class="icon-plus"></i> Aggiungi nuovo servizio</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'facility', 'action' => 'index'), null, true); ?>"><i class="icon-pencil"></i> Modifica / elimina</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> Offerte <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'offers', 'action' => 'new'), null, true); ?>#"><i class="icon-plus"></i> Aggiungi nuovo pacchetto</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'offers', 'action' => 'index'), null, true); ?>"><i class="icon-pencil"></i> Modifica / elimina</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-book icon-white"></i> Prenotazioni <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'reservations', 'action' => 'index'), null, true); ?>"><i class="icon-plus"></i> In arrivo oggi</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'reservations', 'action' => 'search'), null, true); ?>"><i class="icon-pencil"></i> Ricerca avanzata</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav pull-right">
                    <li><a role="button" href="#logoutModal" data-toggle="modal"><i class="icon-off icon-white"></i> Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="logoutModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Logout</h3>
    </div>
    <div class="modal-body">
        <p>Sei sicuro di voler chiudere la finestra?</p>
    </div>
    <div class="modal-footer">
        <a class="btn btn-danger" href="<?php echo $this->url(array('controller' => 'login', 'action' => 'logout'), null, true); ?>">Logout</a>
    </div>
</div>