<?php $this->layout()->setLayout('superadmin'); ?>

<?php echo $this->render('global/topbar_superadmin.phtml'); ?>

<div class="row">
	<div class="span6">
		<h1>Benvenuto <small><?php echo $this->identity->fullname; ?></small></h1>
	</div>
	<div class="span6">
		<a class="btn pull-right" href="add"><i class="icon-plus"></i> Aggiungi un nuovo account</a>
	</div>
</div>

<?php echo $this->render('global/copyright_admin.phtml'); ?>