<?php $this->layout()->setLayout('superadmin'); ?>

<div class="row">
	<div class="six columns centered">
		<h2>Administrator</h2>
		<p>Administrator Reserved: please Login to manage booking.</p>
		<hr />

		<?php if ($this->loginError): ?>
			<div class="alert-box alert">
				<?php echo $this->loginError; ?><a href="" class="close">&times;</a>
			</div>
		<?php endif ?>

		<!-- Login Form -->
		<?php echo $this->html_form; ?>
	</div>
</div>