<?php $this->layout()->setLayout('admin'); ?>

<div class="row">
	<div class="span6 centred">
		<h1>Recupero Password</h1>
		<p>Inserisci l'email con la quale hai effettuato la registrazione.</p>
		<hr />

		<?php if ($this->html_success): ?>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<?php echo $this->html_success; ?>
			</div>
		<?php endif ?>

		<!-- Login Form -->
		<?php echo $this->html_form; ?>
	</div>
</div>