<?php $this->layout()->setLayout('admin'); ?>

<div class="row">
	<div class="span6">
		<h1>Accesso negato</h1>
		<p>Rieffettua login Oppure torna alla <a href="<?php echo $this->serverUrl(); ?>">Homepage</a> del sito.</p>
		<hr />
		<div class="alert alert-error">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			Non sei autorizzato ad accedere a questa pagina
		</div>
	</div>
</div>