<!DOCTYPE HTML>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title>Spiaggia Online 1.0 - Administrator</title>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="/stylesheets/foundation.min.css" />
	<script src="/javascripts/modernizr.foundation.js"></script>
</head>

<body>

    <?php echo $this->layout()->content; ?>
	
	<!-- javascripts -->
	<script src="/javascripts/jquery.js"></script>
	<script src="/javascripts/foundation.min.js"></script>
	<script src="/javascripts/app.js"></script>
</body>
</html>