<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<?php echo $this->headMeta(); ?>
	<title>Spiaggia Online 1.0</title>
	<link rel="stylesheet" href="/css/bootstrap.css">
	<link rel="stylesheet" href="/css/bootstrap-admin.css">
	<link rel="stylesheet" href="/css/bootstrap-dataTables.css">
</head>

<body>

	<div class="container">
		<?php echo $this->layout()->content; ?>
	</div>
	
	<script src="/js/jquery.js"></script>
	<script src="/js/bootstrap.js"></script>
	<script src="/js/jquery.dataTables.js"></script>
	<script src="/js/bootstrap.dataTables.js"></script>
	<script src="/js/superadmin.jquery.js"></script>
</body>
</html>