<?php $this->layout()->setLayout('admin'); ?>

<?php echo $this->render('global/topbar_admin.phtml'); ?>

<div class="row">
	<div class="twelve columns">
	    <h1 class="subheader">Modifica Servizi</h1>
	    <p>...</p>
	    <hr />
	</div>
</div>

<div class="row">
	<div class="seven columns">
	    <?php echo $this->html_form; ?>
	</div>
</div>

<?php echo $this->render('global/copyright_admin.phtml'); ?>