<?php $this->layout()->setLayout('admin'); ?>

<?php echo $this->render('global/topbar_admin.phtml'); ?>

<div class="row">
	<div class="twelve columns">
	    <h1 class="subheader">Servizi</h1>
	    <p>...</p>
	    <hr />
	</div>
</div>

<div class="row">
	<div class="twelve columns">
		<table class="twelve">
			<thead>
				<tr>
					<th>Modifica</th>
					<th>Cancella</th>
					<th>Servizio</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><a href="<?php echo $this->url(array('controller' => 'facility', 'action' => 'edit', 'id' => 0)); ?>" class="button">Modifica</a></td>
					<td><a href="<?php echo $this->url(array('controller' => 'facility', 'action' => 'delete', 'id' => 0)); ?>" class="button">Cancella</a></td>
					<td>...</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<?php echo $this->render('global/copyright_admin.phtml'); ?>