<?php $this->layout()->setLayout('superadmin'); ?>

<?php echo $this->render('global/topbar_superadmin.phtml'); ?>

<div class="row">
	<div class="span6">
		<h1>Gestione Lidi</h1>
	    <p>...</p>
	</div>
	<div class="span6">
		<a class="btn pull-right" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'new')); ?>"><i class="icon-plus"></i> Aggiungi un nuovo Lido</a>
	</div>
</div>

<div class="row">
	<div class="span12">
		<table id="data_tables" class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Modifica</th>
					<th>Cancella</th>
					<th>ID</th>
					<th>Stabilimento Balneare</th>
					<th>Account</th>
					<th>Registrazione</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->users as $row): ?>
				<tr>
					<td><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'fulledit', 'id' => $row['id'])); ?>" class="btn">Modifica</a></td>
					<td><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'delete', 'id' => $row['id'])); ?>" class="btn">Cancella</a></td>
					<td><?php echo $row['id']; ?></td>
					<td><?php echo $this->escape($row['fullname']); ?></td>
					<td><img src="/img/<?php echo $row['status']; ?>.png" alt=""></td>
					<td><?php echo $row['entry']; ?></td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</div>

<?php echo $this->render('global/copyright_admin.phtml'); ?>