<?php $this->layout()->setLayout('admin'); ?>

<?php echo $this->render('global/topbar_admin.phtml'); ?>

<div class="row">
	<div class="span12">
	    <h1 class="subheader">Offerte Speciali</h1>
	    <p>Totale <?php echo count($this->offers); ?></p>
	    <hr />
	</div>
</div>

<div class="row">
	<div class="span12">
		
		<?php if (count($this->offers) > 0): ?>
		<table id="data_tables" class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Modifica</th>
					<th>Cancella</th>
					<th>Offerta</th>
					<th>Stato</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->offers as $row): ?>
				<tr>
					<td><a href="<?php echo $this->url(array('controller' => 'offers', 'action' => 'edit', 'id' => $row['id'])); ?>" class="btn">Modifica</a></td>
					<td>
						<a role="button" href="#deleteModal_<?php echo $row['id']; ?>" data-toggle="modal" class="btn">Cancella</a>
						<div id="deleteModal_<?php echo $row['id']; ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
						    <div class="modal-header">
						        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						        <h3 id="myModalLabel">Eliminazione</h3>
						    </div>
						    <div class="modal-body">
						        <p>Sei sicuro di voler cancellare?</p>
						    </div>
						    <div class="modal-footer">
						        <a class="btn btn-danger" href="<?php echo $this->url(array('controller' => 'offers', 'action' => 'delete', 'id' => $row['id'])); ?>">Cancella</a>
						    </div>
						</div>
					</td>
					<td><?php echo $this->escape($row['name']); ?></td>
					<td><img src="/img/<?php echo $row['status']; ?>.png" alt=""></td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
		<?php else: ?>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  Nessun risultato trovato
			</div>
		<?php endif ?>

	</div>
</div>

<?php echo $this->render('global/copyright_admin.phtml'); ?>